### ISSUE TITLE
tests.multi_timer_test.MultiSocketTest fails

### ISSUE THREAD

**Issue by kdudka** [p/pycurl-archived#19]
```
$ nosetests -v tests/multi_timer_test.py
test_multi_timer (tests.multi_timer_test.MultiSocketTest) ... FAIL

======================================================================
FAIL: test_multi_timer (tests.multi_timer_test.MultiSocketTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kdudka/git/pycurl/tests/multi_timer_test.py", line 84, in test_multi_timer
    self.assertEqual(-1, timers[-1])
AssertionError: -1 != 149999

----------------------------------------------------------------------
Ran 1 test in 0.309s

FAILED (failures=1)
```

It fails on all my machines (Gentoo Linux, Fedora, RHEL) with libcurl-7.24+, which enables the test.  It is not clear to me what the assertion actually says and why it should hold.  There was no such assertion in the original test-case, so I failed to dig the information from its history:

https://github.com/p/pycurl/commit/7bdd907c

**Comment by p** [comment]
The original test case had no assertions. When I ran it on my machine the last timeout was -1, which is how that assertion came into existence. Maybe I will just remove it completely.

**Comment by kdudka** [comment]
Perhaps we should just check that the pycurl.M_TIMERFUNCTION call-back gets called without additional assumptions about the value of its argument?

**Comment by p** [comment]
There is another assertion for the first timeout being positive I believe.

**Comment by kdudka** [comment]
You are right.  Both the assertions 'len(timers) > 0' and 'timers[0] >= 0' should be positive.  The first one checks that the call-back was called at least once.  The assertion 'self.assertEqual(-1, timers[-1])' probably does not hold in general and is a good candidate for removal.
